# Generated by Django 4.0.1 on 2022-01-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tripcity_city_name_trip_cities_trip_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cities',
            field=models.ManyToManyField(to='api.City'),
        ),
    ]
