# Generated by Django 4.0.1 on 2022-01-29 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trip_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
