version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: travel_user
      POSTGRES_DB: travel
      POSTGRES_PASSWORD: travel_123
    volumes:
      - pgdata:/var/lib/posgresql/data
  travel:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      POSTGRES_USER: travel_user
      POSTGRES_DB: travel
      POSTGRES_PASSWORD: travel_123
      SECRET_KEY: django-insecure-e=ac5k9p#@jg4drlsa1)k%o-y+@_-r12=5d)(ky&3*f_t%l0f^
    volumes:
      - ./TravelCompanion:/code
    command: >
      sh -c "python manage.py test api &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
volumes:
  pgdata:
